[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "node src/index.js"
healthcheckPath = "/api/products"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
